USE [SCDBTS_CONSULT]
GO
/****** Object:  StoredProcedure [dbo].[FINANCIAL_DATA]    Script Date: 4/18/2015 3:25:58 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Carlos Chaparro
-- ALTER date: <ALTER Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[FINANCIAL_DATA] 
	(
	@IPA_NUM VARCHAR(max),
	@FROM_MONTH VARCHAR(2), 
    @FROM_YEAR VARCHAR(4),
	@TO_DATE VARCHAR(12),
    @ELEGIBILITY_YEAR VARCHAR(12),
	@ELEGIBILITY_MONTH VARCHAR(12)
)
AS BEGIN
	
 SET NOCOUNT ON;

	DECLARE @PIPA_NUM VARCHAR(MAX)
	SET @PIPA_NUM = @IPA_NUM

	DECLARE @PFROM_DATE varchar(10)
	DECLARE @PTO_DATE VARCHAR(10)

	SET  @PIPA_NUM = @IPA_NUM

    --Carrier Risk
	DECLARE @INCURRE_CLAIMS money;
	--DECLARE	@IBNR_CARRIER_RISK money;
	DECLARE	@TOTAL_CARRIER_RISK money;
	DECLARE	@STOPLOSS_FUND_BALANCE money;
	DECLARE	@PMG_STOPLOSS_FUND_BALANCE money;
	DECLARE	@SUB_TOTAL_PMG_FUND_BALANCE money;
	DECLARE	@TOTAL_QUALITY_PROGRAM_OTHER_CREDITS money;
	DECLARE	@TOTAL_PMG_FUND_BALANCE money;
	--DECLARE	@SURPLUS_PAYMENTS money;
	DECLARE	@PMG_FUND_BALANCE_WITHHELD money;
	DECLARE	@TOTAL_PAYMENT_TO_PMG money;
	DECLARE	@TOTAL_PAYMENTS money;
		--Execute CLAIM_MASTER
	DECLARE @PAY_AMT money;
	DECLARE @PCP_BUDGET money = 0.00;
	DECLARE @PAID_PCP_CAP money = 0.00;
	DECLARE @PHYSICAL_HEALTH_BUDGET money = 0.00;
	DECLARE @STOPLOSS_BUDGET money = 0.00;
			
	DECLARE	@TOTAL_PCP_BUDGET money;
	DECLARE	@PCP_FUND_BALANCE money;
	DECLARE	@TOTAL_PGM_RISK money;
	DECLARE	@PHYSICAL_HEALTH_FUND_BALANCE money;
	DECLARE	@PMG_PHYSICAL_HEALTH_FUND_BALANCE money;
	DECLARE	@TOTAL_PMG_RISK_BALANCE money;
	DECLARE	@IBNR money;


	DECLARE @STOPLOSS_INCURREDCLAIMS money;
    DECLARE @LIVES MONEY;
    DECLARE @FINES_WITHHOLDS MONEY;
    DECLARE @PRIMARY_CARE_SERVICES MONEY;
    DECLARE @HOSPITAL_FIX_PAYMENTS MONEY;
    DECLARE @RPS_MEDICAL_SERVICE MONEY;
    DECLARE @DIABETIC_SOLUTIONS MONEY;
    DECLARE @UROLOGIST_SPECIAL_AGREEMENT MONEY;
    DECLARE @WITHHOLDING_INCENTIVE_HOSPITAL MONEY;
    DECLARE @EXTENDED_HOURS_PROGRAM MONEY;
    DECLARE @SHARING MONEY;
    DECLARE @SPECIAL_PEYMENTS MONEY;
    DECLARE @QUALITY_PROGRA_CREDITS MONEY;
    DECLARE @OTHE_CREDITS MONEY;
    DECLARE @VACCINE_AMBULANCE_SERVICES MONEY;
    DECLARE @SURPLUS_PAYMENTS MONEY;
    DECLARE @SPECIAL_AGREEMENT_BUDGET MONEY;
    DECLARE @PARTIAL_PAYMENTS MONEY;
    DECLARE @SPECIAL_PAYMENTS_SPECIAL_AGREEMENTS MONEY;
    DECLARE @OTHER_ADJUSMENTS MONEY;
    DECLARE @STOPLOSS_LIMIT MONEY;
	DECLARE @SPECIAL_PAYMENTS MONEY;
	DECLARE @INCURRED_CLAIM MONEY;
	DECLARE @FROM_DATE VARCHAR(10);
	DECLARE	@ELEGIBILITY_DATE VARCHAR(10);
	DECLARE @MEMBERSHIP MONEY;
	DECLARE @MEMBERSHIP_ADJUSTMENT MONEY;
	DECLARE @TOTAL_MEMBERSHIP MONEY;
	DECLARE @PER_CAP_SUPPLEMENTARY_DATA MONEY;
	DECLARE @STOPLOSS MONEY;

	

	SET @FROM_DATE = @FROM_YEAR + '-' + @FROM_MONTH + '-01';
	SET @ELEGIBILITY_DATE = @ELEGIBILITY_YEAR + '-' + @ELEGIBILITY_MONTH + '-01';


	SELECT @STOPLOSS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'STO' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE

--SET @STOPLOSS = 15000;--Delete on production			

SELECT @PAY_AMT = SUM(PAY_AMT)
	 FROM CLAIM_MASTER WHERE IPA_NUM = @PIPA_NUM 
	 AND SERV_DATE BETWEEN @FROM_DATE AND @TO_DATE;
	
--MISSING COLUMNS WILL

	SELECT @PCP_BUDGET = SUM(PHARM_FUND) 
	FROM CAP_MASTER 
	WHERE IPA_NUM = @PIPA_NUM AND FILE_DATE BETWEEN @FROM_DATE AND @TO_DATE;


SELECT @PAID_PCP_CAP = SUM(MED_FUND) FROM CAP_MASTER WHERE IPA_NUM = @PIPA_NUM AND FILE_DATE BETWEEN @FROM_DATE AND @TO_DATE;


	SELECT @PHYSICAL_HEALTH_BUDGET = SUM(INS_FUND) 
	FROM CAP_MASTER 
	WHERE IPA_NUM = @PIPA_NUM AND FILE_DATE BETWEEN @FROM_DATE AND @TO_DATE


 	SELECT @STOPLOSS_BUDGET = SUM(BUDGET) 
	FROM CAP_MASTER 
	WHERE IPA_NUM = @PIPA_NUM AND FILE_DATE BETWEEN @FROM_DATE AND @TO_DATE
 

	SELECT @LIVES =  SUM(AMOUNT) FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'LVS' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE

	SELECT @MEMBERSHIP_ADJUSTMENT =  SUM(AMOUNT) FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'LVA' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE

	SELECT @TOTAL_MEMBERSHIP = @LIVES + @MEMBERSHIP_ADJUSTMENT


SELECT @FINES_WITHHOLDS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PFW' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @PRIMARY_CARE_SERVICES = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'POA' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @HOSPITAL_FIX_PAYMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PHP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @DIABETIC_SOLUTIONS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PDP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @UROLOGIST_SPECIAL_AGREEMENT = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PUA' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @WITHHOLDING_INCENTIVE_HOSPITAL = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PWP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @EXTENDED_HOURS_PROGRAM = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PEP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @SHARING = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PS' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @SPECIAL_PAYMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @QUALITY_PROGRA_CREDITS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'QPC' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @OTHE_CREDITS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'OTC' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @VACCINE_AMBULANCE_SERVICES = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PVA' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @SURPLUS_PAYMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SSP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE 


SELECT @SPECIAL_AGREEMENT_BUDGET = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SAB' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE 


	SELECT @PARTIAL_PAYMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SAP' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @SPECIAL_PAYMENTS_SPECIAL_AGREEMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SAS' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


SELECT @OTHER_ADJUSMENTS = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SAO' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


	SELECT @STOPLOSS_LIMIT = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'SLL' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE 


	SELECT @INCURRED_CLAIM = SUM(STOPLOSS)
		FROM (
			SELECT MEM_NUM, SUM(PAY_AMT) - cast(@STOPLOSS as decimal) STOPLOSS
				FROM [SCDBTS_CONSULT].[dbo].[CLAIM_MASTER]
				WHERE IPA_NUM IN (@PIPA_NUM) AND FILE_DATE BETWEEN @ELEGIBILITY_DATE AND @TO_DATE
			GROUP BY MEM_NUM
			HAVING SUM(PAY_AMT) > cast(@STOPLOSS as decimal)) T


SELECT @RPS_MEDICAL_SERVICE = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PMS' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE


		SELECT @VACCINE_AMBULANCE_SERVICES = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'PVA' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE

 
	SELECT @IBNR = SUM(AMOUNT)
	FROM PER_CAP_SUPPLEMENTARY_DATA 
	WHERE TYPE = 'IBN' AND IPA_ID = @PIPA_NUM AND INCURRED_DATE BETWEEN @FROM_DATE AND @TO_DATE

		

select @FROM_MONTH, 
     @FROM_YEAR,
     @PCP_BUDGET,
	 @PAID_PCP_CAP,
	 @LIVES,
     @FINES_WITHHOLDS,
	 @OTHER_ADJUSMENTS,
	 @TOTAL_PCP_BUDGET,
	 @PCP_FUND_BALANCE,
	 @PHYSICAL_HEALTH_BUDGET,
	 @PAY_AMT,
     @HOSPITAL_FIX_PAYMENTS,
     @RPS_MEDICAL_SERVICE,
	 @DIABETIC_SOLUTIONS,
     @UROLOGIST_SPECIAL_AGREEMENT,
     @WITHHOLDING_INCENTIVE_HOSPITAL,
     @EXTENDED_HOURS_PROGRAM,
	 @VACCINE_AMBULANCE_SERVICES,
	 @TOTAL_PGM_RISK,
	 @IBNR,
     @PHYSICAL_HEALTH_FUND_BALANCE,
	 @SHARING,
     @PMG_PHYSICAL_HEALTH_FUND_BALANCE,
	 @TOTAL_PMG_RISK_BALANCE,
	 @STOPLOSS_BUDGET,
	 @INCURRE_CLAIMS,
	 @SPECIAL_PAYMENTS,
	 @IBNR,
	 @TOTAL_CARRIER_RISK,
	 @STOPLOSS_FUND_BALANCE,
     @SHARING,
	 @PMG_STOPLOSS_FUND_BALANCE,
	 @SUB_TOTAL_PMG_FUND_BALANCE,
	 @QUALITY_PROGRA_CREDITS,
     @OTHE_CREDITS,
	 @TOTAL_QUALITY_PROGRAM_OTHER_CREDITS,
	 @TOTAL_PMG_FUND_BALANCE,
     @SURPLUS_PAYMENTS,
	 @PMG_FUND_BALANCE_WITHHELD,
	 @TOTAL_PAYMENT_TO_PMG,
	 @TOTAL_PAYMENTS,
     @SURPLUS_PAYMENTS,
	 @INCURRED_CLAIM,
	 @MEMBERSHIP,
	 @MEMBERSHIP_ADJUSTMENT,
	 @TOTAL_MEMBERSHIP;

END

		